name: Build Docker
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract lowercase repository name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
        id: repository
      - name: GET Factorio image versions
        shell: bash
        run: |
          echo "FACTORIO_STABLE_VERSION=$(wget -q 'https://raw.githubusercontent.com/factoriotools/factorio-docker/master/buildinfo.json' -O - | jq -r 'to_entries[] | select(.value.tags | index("stable")) | .key')" >> $GITHUB_OUTPUT
          echo "FACTORIO_LATEST_VERSION=$(wget -q 'https://raw.githubusercontent.com/factoriotools/factorio-docker/master/buildinfo.json' -O - | jq -r 'to_entries[] | select(.value.tags | index("latest")) | .key')" >> $GITHUB_OUTPUT
        id: factorio_version
      - name: Docker stable meta
        id: meta_stable
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/${{ steps.repository.outputs.lowercase }}
          tags: |
            type=raw,value=${{ steps.factorio_version.outputs.FACTORIO_STABLE_VERSION }},enable={{is_default_branch}}
            type=raw,value=stable,enable={{is_default_branch}}
            type=raw,value={{branch}}-${{ steps.factorio_version.outputs.FACTORIO_STABLE_VERSION }}
            type=raw,value={{branch}}-stable
      - name: Docker latest meta
        id: meta_latest
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/${{ steps.repository.outputs.lowercase }}
          tags: |
            type=raw,value=${{ steps.factorio_version.outputs.FACTORIO_LATEST_VERSION }},enable={{is_default_branch}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value={{branch}}-${{ steps.factorio_version.outputs.FACTORIO_LATEST_VERSION }}
            type=raw,value={{branch}}-latest
            type=raw,value={{branch}}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            "FACTORIO_VERSION=${{ steps.factorio_version.outputs.FACTORIO_STABLE_VERSION }}"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_stable.outputs.tags }}
          labels: ${{ steps.meta_stable.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ steps.repository.outputs.lowercase }}:${{ steps.factorio_version.outputs.FACTORIO_STABLE_VERSION }}
          cache-to: type=inline
          platforms: linux/amd64
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            "FACTORIO_VERSION=${{ steps.factorio_version.outputs.FACTORIO_LATEST_VERSION }}"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_latest.outputs.tags }}
          labels: ${{ steps.meta_latest.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ steps.repository.outputs.lowercase }}:${{ steps.factorio_version.outputs.FACTORIO_LATEST_VERSION }}
          cache-to: type=inline
          platforms: linux/amd64
